# Generated by Django 3.0.8 on 2020-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_tag1', models.CharField(default='', max_length=20, verbose_name='клас')),
                ('test_title', models.CharField(max_length=150, verbose_name='назва')),
                ('test_eng', models.TextField(blank=True, default='', max_length=20000, verbose_name='переклад')),
                ('test_ukr', models.TextField(blank=True, default='', max_length=20000, verbose_name='українські слова')),
            ],
            options={
                'verbose_name': 'стаття',
                'verbose_name_plural': 'статті',
            },
        ),
    ]
