# Generated by Django 3.1.2 on 2021-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тести'},
        ),
        migrations.AddField(
            model_name='test',
            name='test_time',
            field=models.CharField(default='10', max_length=2, verbose_name='час'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_tag1',
            field=models.CharField(default='10B', max_length=20, verbose_name='клас'),
        ),
    ]
