# Generated by Django 3.0.8 on 2020-07-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=150, verbose_name='назва статті')),
                ('article_text', models.TextField(verbose_name='текст статті')),
                ('pub_date', models.DateTimeField(verbose_name='дата публікації')),
            ],
        ),
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='імя автора')),
                ('coment_text', models.CharField(max_length=200, verbose_name='текст комента')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
