# Generated by Django 3.0.8 on 2020-08-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200806_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_sim1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_sim2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_sim3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_sim4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_sim5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_sim6',
        ),
        migrations.AddField(
            model_name='article',
            name='article_f1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула1'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_f2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула2'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_f3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула3'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_f4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула4'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_f5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула5'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_f6',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула6'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент1опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент2опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент3опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var4',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент4опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var5',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент5опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var6',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент6опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_var7',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент7опис'),
        ),
    ]
