# Generated by Django 3.0.8 on 2020-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200814_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_2f1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула1'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2f2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула2'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2f3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула3'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2f4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула4'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2f5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула5'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2f6',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула6'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2text',
            field=models.CharField(blank=True, max_length=100, verbose_name='формула2'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент1опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент2опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент3опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var4',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент4опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var5',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент5опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var6',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент6опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2var7',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент7опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3f1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула1'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3f2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула2'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3f3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула3'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3f4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула4'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3f5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула5'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3f6',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='формула6'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент1опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент2опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент3опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var4',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент4опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var5',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент5опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var6',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент6опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3var7',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='елемент7опис'),
        ),
    ]
