# Generated by Django 3.0.8 on 2020-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200819_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_2text',
            field=models.CharField(blank=True, max_length=100, verbose_name='головна формула3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.CharField(max_length=100, verbose_name=' головна формула'),
        ),
    ]
