# Generated by Django 3.0.8 on 2020-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200819_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_3text',
            field=models.CharField(blank=True, max_length=100, verbose_name='головна формула3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_2text',
            field=models.CharField(blank=True, max_length=100, verbose_name='головна формула2'),
        ),
    ]
