# Generated by Django 3.0.8 on 2020-08-19 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200819_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_3f6',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 8, 19, 9, 14, 42, 8751, tzinfo=utc), max_length=100, verbose_name='формула6'),
        ),
    ]
