# Generated by Django 3.0.8 on 2020-08-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200819_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_2f1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2f2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2f3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2f4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2f5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2f6',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var6',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_2var7',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3f1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3f2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3f3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3f4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3f5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3f6',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var6',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_3var7',
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag1',
            field=models.CharField(default='', max_length=20, verbose_name='предмет'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag2',
            field=models.CharField(default='', max_length=20, verbose_name='група'),
        ),
    ]
