# Generated by Django 3.0.8 on 2020-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200819_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_lesson', models.CharField(blank=True, default='', max_length=30, verbose_name='формула1')),
                ('obj_topic1', models.CharField(blank=True, default='', max_length=30, verbose_name='тема1')),
                ('obj_topic2', models.CharField(blank=True, default='', max_length=30, verbose_name='тема2')),
                ('obj_topic3', models.CharField(blank=True, default='', max_length=30, verbose_name='тема3')),
                ('obj_topic4', models.CharField(blank=True, default='', max_length=30, verbose_name='тема4')),
                ('obj_topic5', models.CharField(blank=True, default='', max_length=30, verbose_name='тема5')),
                ('obj_topic6', models.CharField(blank=True, default='', max_length=30, verbose_name='тема6')),
                ('obj_topic7', models.CharField(blank=True, default='', max_length=30, verbose_name='тема7')),
                ('obj_topic8', models.CharField(blank=True, default='', max_length=30, verbose_name='тема8')),
                ('obj_topic9', models.CharField(blank=True, default='', max_length=30, verbose_name='тема9')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'теми',
            },
        ),
    ]
