# Generated by Django 3.0.8 on 2020-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic2',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic3',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic4',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic5',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic6',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic7',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic8',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic9',
        ),
        migrations.AlterField(
            model_name='obj',
            name='obj_lesson',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='obj_topic1',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='тема'),
        ),
    ]
