# Generated by Django 3.0.8 on 2020-08-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200820_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obj',
            old_name='obj_topic1',
            new_name='obj_topic',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
