# Generated by Django 3.0.8 on 2020-08-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200820_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obj',
            old_name='obj_topic1',
            new_name='obj_topic',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic10',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic11',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic12',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic2',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic3',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic4',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic5',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic6',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic7',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic8',
        ),
        migrations.RemoveField(
            model_name='obj',
            name='obj_topic9',
        ),
    ]
