# Generated by Django 3.0.8 on 2020-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20200821_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_var1',
            field=models.CharField(blank=True, default='₀₁₂₃₄₅₆₇₈₉ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨαβγδζηθικλμνξοπρστυφχψω', max_length=200, verbose_name='елемент1опис'),
        ),
    ]
